apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wellbore-domain-services-worker
  namespace: osdu-flux
spec:
  dependsOn:
    - name: wellbore-domain-services
  targetNamespace: osdu
  interval: 30m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./software/charts/osdu-spi-service
      sourceRef:
        kind: GitRepository
        name: osdu-spi-stack-system
  values:
    image:
      repository: ${WELLBORE_DOMAIN_SERVICES_WORKER_IMAGE_REPOSITORY}
      tag: "${WELLBORE_DOMAIN_SERVICES_WORKER_IMAGE_TAG}"
      digest: "${WELLBORE_DOMAIN_SERVICES_WORKER_IMAGE_DIGEST}"
    nodeSelector:
      spi-pool: osdu
    tolerations:
      - key: workload
        operator: Equal
        value: "osdu"
        effect: NoSchedule
    probes:
      liveness:
        path: /liveness
        port: 8080
        initialDelaySeconds: 20
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3
      readiness:
        path: /readiness
        port: 8080
        initialDelaySeconds: 10
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 6
    resources:
      requests:
        cpu: 100m
        memory: 350Mi
      limits:
        cpu: "1"
        memory: 1Gi
    env:
      - name: CLOUD_PROVIDER
        value: az
      - name: SERVICE_NAME
        value: wellbore-domain-services-worker
      - name: OPENAPI_PREFIX
        value: /api/wdms-worker
      - name: SERVICE_HOST_PARTITION
        value: http://partition/api/partition
      - name: USE_PARTITION_SERVICE
        value: enabled
      - name: AZ_LOGGER_LEVEL
        value: INFO
